# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.6.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - colorama==0.4.6
    - numpy==2.0.0
    - pandas==2.2.2
    - robotframework==4.1.1
    - robotframework-pythonlibcore==4.4.1
    - robotframework-requests==0.9.7
    - robotframework-sapguilibrary==1.1
    - robotframework-seleniumlibrary==6.5.0
    - robotframework-seleniumtestability==2.1.0
    - rpaframework==28.6.1
    - rpaframework-core==11.3.2
    - rpaframework-pdf==7.3.2
    - rpaframework-windows==7.5.1
    - selenium==4.15.2
    - uiautomation==2.0.20
    - urllib3==2.2.2
    - webdriver-manager==4.0.1
    - pywin32==306